services:


  client:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: otz-client
    # container_name: huruma-frontendv2
    volumes:
      - . :/usr/src/app
      - /usr/src/app/node_modules

    # deploy:
    #   # mode: replicated
    #   # replicas: 5
    #   # placement:
    #   #   max_replicas_per_node: 1
    #   # update_config:
    #   #   parallelism: 2
    #   #   delay: 10s
    #   # restart_policy:
    #   #   condition: on-failure    
    #   resources:
    #     limits:
    #       cpus: '0.50'
    #       # memory: 1000M

    ports:
      - "3000:3000"

