FROM node:20-alpine AS  builder

# ARG NODE_ENV

# ENV NODE_ENV ${NODE_ENV}

WORKDIR /usr/src/app

COPY package.json ./

RUN npm install 

COPY . .


RUN yarn run build

FROM node:20-alpine

# Set the working directory
WORKDIR /usr/src/app


# Copy the built application from the builder stage
COPY --from=builder /usr/src/app .


EXPOSE 3000

ENV CHOKIDAR_USEPOLLING=true

CMD ["npm","start"]