FROM node:22-alpine

# ARG NODE_ENV

# ENV NODE_ENV ${NODE_ENV}

WORKDIR /usr/src/app

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile

COPY . .


RUN yarn run build

CMD ["npm","start"]