name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [21.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm' # Enables pnpm-specific caching

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Cache pnpm store
        uses: pnpm/action-setup@v2
        with:
          version: 'latest'
          run_install: true  # Runs `pnpm install` automatically and restores cached dependencies

      - name: Run Lint
        run: pnpm run lint

      - name: Run Tests
        run: pnpm run test

      - name: Build Project (if present)
        run: pnpm build --if-present
